MOBILE-3905: Swipe navigation tests
moodlehq/moodle-local_moodlemobileapp pull request #48
Opened 2021-11-09 15:13 UTC by NoelDeMartin

Related PRs in other branches: #45 #46 #47

2021-11-12 07:59 UTC, dpalou requested changes

2021-11-12 07:59 UTC, dpalou commented on tests/behat/app_behat_runtime.js
> +        const activeElement = [...document.querySelectorAll(`.ion-page:not(.ion-page-hidden) ${selector}`)].pop();
Instead of using "[...items]" I usually do "Array.from(items)" to convert the NodeList to a regular array. I think it's better to understand what it does, specially if you aren't an experienced JS developer.

2021-11-12 07:59 UTC, dpalou commented on tests/behat/navigation_gestures.feature
> +    Then I should find "Student First" in the app
Maybe we should test that nothing happens if you swipe right when you're in the first item? What do you think?

2021-11-15 09:07 UTC, NoelDeMartin commented on tests/behat/app_behat_runtime.js
> +        const activeElement = [...document.querySelectorAll(`.ion-page:not(.ion-page-hidden) ${selector}`)].pop();
Ok, I've changed it, I think it looks better too. I didn't remember that function existed and I am used to the spread operator.

2021-11-15 09:07 UTC, NoelDeMartin commented on tests/behat/navigation_gestures.feature
> +    Then I should find "Student First" in the app
Yes, that's already what this code is doing. The last two assertions are on the same student, which is the first.

2021-11-15 09:10 UTC, dpalou commented on tests/behat/navigation_gestures.feature
> +    Then I should find "Student First" in the app
Ok, I'm blind lol

2021-11-15 09:10 UTC, dpalou approved these changes

2021-11-15 09:12 UTC, merged