MOBILE-3934: Test competency and grades navigation
moodlehq/moodle-local_moodlemobileapp pull request #61
Opened 2022-01-13 12:17 UTC by NoelDeMartin

2022-01-17 13:42 UTC, dpalou requested changes

2022-01-17 13:42 UTC, dpalou commented on grade/tests/behat/app_navigation.feature
> +
I think it would be interesting to also check that a student cannot view another student grades (going to Participants like it's done with teacher).

2022-05-13 10:29 UTC, crazyserver commented
@NoelDeMartin please migrate those test to the app repo and close this Pull request.

2022-05-16 07:11 UTC, NoelDeMartin commented
Thanks @crazyserver for the heads up. I'm still trying to get generators into core, so until [MDL-74655](https://tracker.moodle.org/browse/MDL-74655) and [MDL-74613](https://tracker.moodle.org/browse/MDL-74613) are fixed I'll leave this here.

2022-05-30 08:52 UTC, NoelDeMartin commented on grade/tests/behat/app_navigation.feature
> +
I've applied your suggestion in the new PR https://github.com/moodlehq/moodleapp/pull/3296

2022-05-30 08:52 UTC, NoelDeMartin commented
Closed in favour of https://github.com/moodlehq/moodleapp/pull/3294 and https://github.com/moodlehq/moodleapp/pull/3296.

2022-05-30 08:52 UTC, closed without merging