Integration pau
moodlehq/moodle-local_moodlemobileapp pull request #71
Opened 2022-02-22 21:55 UTC by crazyserver

2022-02-22 21:56 UTC, crazyserver commented
Beware some tests need changes on the app to be fixed.

2022-02-23 09:10 UTC, NoelDeMartin requested changes
I found some minor things to improve, but overall I think the code can be merged.

2022-02-23 09:10 UTC, NoelDeMartin commented on tests/behat/app_behat_runtime.js
> +     * @param {string} containerName Whether to search only inside an specific container content.
`an specific container content` --> `a specific container`.

2022-02-23 09:10 UTC, NoelDeMartin commented on tests/behat/app_behat_runtime.js
> +     * @param {string} containerName Whether to search only inside an specific container.
`an specific container` --> `a specific container`

2022-02-23 09:10 UTC, NoelDeMartin commented on tests/behat/app_behat_runtime.js
> +    const getCurrentTopCotainerElement = function (containerName) {
`getCurrentTopCotainerElement` --> `getCurrentTopContainerElement`

2022-02-23 09:10 UTC, NoelDeMartin commented on tests/behat/app_behat_runtime.js
>          return elements;
I think it's better to do `return elements.map(({ element }) => element);` here to avoid changing the signature of the method. It doesn't seem like we're using `exact` outside of this method anyways.

2022-02-23 09:44 UTC, crazyserver commented on tests/behat/app_behat_runtime.js
>          return elements;
The problem here is that it's a recursive function.. and it needs the exact attribute.

2022-02-23 09:46 UTC, NoelDeMartin commented on tests/behat/app_behat_runtime.js
>          return elements;
In that case, you can create an auxiliar method that is actually recursive and keep this method with the same signature.

2022-02-23 10:00 UTC, crazyserver commented on tests/behat/behat_app.php
> +     * @Then /^I should( not)? find (".+")( inside the .+ content)? in the app$/
Done!

2022-02-23 10:19 UTC, crazyserver commented on tests/behat/app_behat_runtime.js
>          return elements;
ok then! Done!

2022-02-23 10:30 UTC, NoelDeMartin approved these changes

2022-02-23 10:31 UTC, merged